# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15tmrqLT3hKRLFYfwOVTNpC9XTGd60fwN
"""

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,8])
y=np.array([0,350])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,8,4])
y=np.array([0,350,5])
z=np.array([0,650,30])
plt.plot(x,y,z)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,8,4,3,23,34,45,67])
y=np.array([0,350,5,1,12,34,567,76])
plt.plot(x,y,z)
plt.show()